services:
  crypto:
    container_name: SpectreCrypto
    build:
      context: ./crypto
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: sh -c "gunicorn --bind 0.0.0.0:${SERVER_PORT} server:app --workers 3"
    restart: always
    networks:
      custom_network:
        ipv4_address: 10.12.0.11
    
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/24